### ISSUE TITLE
Folder refactoring

### ISSUE THREAD

**Issue by sandunisuru** [Sandun-Isuru-Niraj/Covid-19-SL-Tracker#12]
This project needs some folder structure refactoring to done. It's nice if you can go a structure like this.
![image](https://user-images.githubusercontent.com/27560724/95649254-3e676f80-0afa-11eb-91d1-11129010f633.png)

**Comment by thisni1s** [comment]
Implemented with [this](https://github.com/Sandun-Isuru-Niraj/Covid-19-SL-Tracker/pull/15) pr

**Comment by sandunisuru** [comment]
Thanks @NilsKempen for resolving the issue. I'm closing this now. Good Luck for your future. Hail FOSS
